# Generated by Django 2.1.1 on 2018-09-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_bt_id', models.IntegerField(blank=True, default=None, null=True)),
                ('equipment_category', models.CharField(default='', max_length=255)),
                ('equipment_subcategory', models.CharField(default='', max_length=255)),
                ('manufacturer', models.CharField(default='', max_length=255)),
                ('serial_number', models.CharField(default='', max_length=255)),
                ('model_number', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstequipmentinspectiontype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstequipmentitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstequipmenttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
    ]
