# Generated by Django 2.1.1 on 2018-09-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_bt_id', models.IntegerField(blank=True, default=None, null=True)),
                ('default_status', models.IntegerField()),
                ('status', models.IntegerField()),
                ('doc_authority_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_authority_company', to='accounts.Company')),
                ('doc_authority_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_authority_person', to='accounts.Person')),
                ('doc_request_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_request_company', to='accounts.Company')),
                ('doc_request_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_request_person', to='accounts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_bt_id', models.IntegerField(blank=True, default=None, null=True)),
                ('department', models.CharField(choices=[('Inspection', 'Inspection'), ('Engineering', 'Engineering')], default='Inspection', max_length=255)),
                ('project_type', models.CharField(choices=[('Equipment Inspection', 'Equipment Inspection'), ('Engineering Design', 'Engineering Design')], default='Inspection', max_length=255)),
                ('province', models.CharField(choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba')], default='Alberta', max_length=255)),
                ('title', models.CharField(default='Inspection of', max_length=255)),
                ('project_number', models.CharField(default='AE218', max_length=255)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('project_terms', models.CharField(choices=[('Lump Sum', 'Lump Sum'), ('Monthly', 'Monthly')], default='Lump Sum', max_length=255)),
                ('purchase_order', models.CharField(default='PO', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Started', 'Not Started'), ('Completed', 'Completed')], default='Active', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='accounts.Company')),
                ('client_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contact', to='accounts.Person')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.Company')),
                ('project_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='accounts.Person')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name_plural': 'Inspections',
                'verbose_name': 'Inspection',
            },
        ),
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('inspection_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='inspections.Inspection')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_bt_id', models.IntegerField(blank=True, default=None, null=True)),
                ('default_status', models.IntegerField()),
                ('status', models.IntegerField()),
                ('proj_authority_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_authority_company', to='accounts.Company')),
                ('proj_authority_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_authority_person', to='accounts.Person')),
                ('proj_request_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_request_company', to='accounts.Company')),
                ('proj_request_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_request_person', to='accounts.Person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Inspection')),
            ],
        ),
        migrations.CreateModel(
            name='lstDocumentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
                ('Abbr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskdescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
                ('Abbr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
                ('Abbr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lsttaskrelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lstunittype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('Name', models.IntegerField()),
                ('NameText', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_id', models.IntegerField()),
                ('ParentTask', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('Level', models.IntegerField()),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('EstHours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ActHours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Comments', models.CharField(max_length=255)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='inspections.lsttaskcategory')),
                ('Description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='inspections.lsttaskdescription')),
                ('Detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='inspections.lsttaskdetail')),
                ('Phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase', to='inspections.lstPhase')),
                ('RateUnits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateunits', to='inspections.lstunit')),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Resource', to='accounts.Person')),
            ],
        ),
        migrations.AddField(
            model_name='lstunit',
            name='Type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unittype', to='inspections.lstunittype'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='documenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenttype', to='inspections.lstDocumentTypes'),
        ),
        migrations.AddField(
            model_name='inspectiondocument',
            name='inspection_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='inspections.Inspection'),
        ),
        migrations.AddField(
            model_name='documentpermissions',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.InspectionDocument'),
        ),
    ]
